config/routes.rb
Rails.application.routes.draw do
  root to: 'courses#index'

  resource :session, only: %i[new create destroy]

  resources :courses, only: %i[index new create show] do
    resource :proposal, only: %i[create destroy]
    resource :vote,     only: %i[create destroy]
  end

  resources :teachers, only: %i[new create]

  resources :proposals, only: %i[] do
    resource :vote, only: %i[create destroy]
  end

  if Rails.env.test?
    namespace :test do
      post :session, to: 'sessions#create'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  with_options dependent: :destroy do
    has_many :proposals
    has_many :votes, as: :votable
  end

  has_many :teachers, through: :proposals

  validates_presence_of :title

  validates_uniqueness_of :title, case_sensitive: false
end

app/models/proposal.rb
class Proposal < ApplicationRecord
  with_options counter_cache: true do
    belongs_to :course
    belongs_to :teacher
  end

  has_many :votes, as: :votable, dependent: :destroy

  validates_presence_of :course
  validates_presence_of :teacher

  validates_uniqueness_of :teacher_id, scope: :course_id
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_secure_password

  with_options dependent: :destroy do
    has_many :proposals
    has_many :votes, foreign_key: 'voter_id'
  end

  has_many :courses, through: :proposals

  validates_uniqueness_of :email, case_sensitive: false

  validates_presence_of :email
  validates_presence_of :name
  validates_presence_of :password
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :votable, polymorphic: true, counter_cache: true
  belongs_to :voter, class_name: 'Teacher'

  validates_uniqueness_of :voter_id, scope: %i[votable_id votable_type]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_teacher

  def authenticate_teacher
    redirect_to new_session_path unless current_teacher
  end

  def current_teacher
    @current_teacher ||= Teacher.find_by(id: session[:current_teacher_id])
  end
  helper_method :current_teacher
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  expose :courses, -> { Course.includes(:votes).order(created_at: :desc) }

  def index
    courses
  end

  def new
    @course = Course.new
  end

  def show
    @course = Course.find(params[:id])

    @proposals =
      @course.proposals.includes(:teacher, :votes).order(created_at: :desc)
  end

  def create
    @course = current_teacher.courses.create(course_params)

    if @course.errors.blank?
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def course_params
    params.require(:course).permit(:title)
  end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  expose :course

  def create
    course.proposals.create(teacher: current_teacher)

    redirect_to request.referer || root_path
  end

  def destroy
    course.proposals.where(teacher: current_teacher).destroy_all

    redirect_to request.referer || root_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_teacher, only: %i[new create]

  expose :teacher

  def new
    teacher
  end

  def create
    teacher = Teacher.find_by(email: session_params[:email])

    if teacher.try(:authenticate, session_params[:password])
      session[:current_teacher_id] = teacher.id

      redirect_to root_path
    else
      flash[:alert] =
        'The email and password you entered did not match our records.'

      redirect_to new_session_path
    end
  end

  def destroy
    session[:current_teacher_id] = nil

    redirect_to new_session_path
  end

  private

  def session_params
    params.require(:teacher).permit(:email, :password)
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  skip_before_action :authenticate_teacher, only: %i[new create]

  expose :teacher

  def new
    teacher
  end

  def create
    if teacher.save
      session[:current_teacher_id] = teacher.id

      redirect_to root_path
    else
      render :new, status: :bad_request
    end
  end

  private

  def teacher_params
    params.require(:teacher).permit(:email, :name, :password)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  expose :votable, model: -> { infer_model }

  def create
    votable.votes.create(voter: current_teacher)

    redirect_to request.referer || root_path
  end

  def destroy
    votable.votes.where(voter: current_teacher).destroy_all

    redirect_to request.referer || root_path
  end

  private

  def infer_model
    request.path.split('/').second&.classify&.constantize
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include BulmaFormHelpers
end

app/helpers/bulma_form_helpers.rb
module BulmaFormHelpers
  class ActionView::Helpers::FormBuilder
    include ActionView::Helpers::FormTagHelper
    include ActionView::Context

    def bulma_text_field_with_label(name)
      content_tag :div, class: 'field' do
        [
          bulma_label(name),
          content_tag(:div, class: 'control') { bulma_text_field(name) },
          bulma_help_text(name)
        ]
          .sum
      end
    end

    def bulma_password_field_with_label(name)
      content_tag :div, class: 'field' do
        [
          bulma_label(name),
          content_tag(:div, class: 'control') { bulma_password_field(name) },
          bulma_help_text(name)
        ]
          .sum
      end
    end

    def bulma_label(name)
      class_name =
        "label is-uppercase is-size-7 #{@object.errors[name].any? ? 'has-text-primary' : ''}"

      label name, name.capitalize, class: class_name
    end

    def bulma_text_field(name)
      class_name = "input #{@object.errors[name].any? ? 'is-primary' : ''}"

      text_field name, class: class_name
    end

    def bulma_password_field(name)
      class_name = "input #{@object.errors[name].any? ? 'is-primary' : ''}"

      password_field name, class: class_name
    end

    def bulma_help_text(name)
      content_tag(:p, class: 'help is-primary has-text-primary') do
        @object.errors[name].first
      end
    end

    def bulma_submit(value)
      submit value, class: 'button is-primary'
    end
  end
end

app/views/application/_navbar.html.erb
<nav class="navbar is-fixed-top" role="navigation" aria-label="main navigation">
  <div class="container">
    <div class="navbar-brand">
      <%= link_to root_path, class: "navbar-item" do %>
        <%= image_tag "logo.png" %>
      <% end %>

      <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div class="navbar-menu">
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
            <% if current_teacher %>
              <%= link_to "Sign Out", session_path, method: :delete, class: "button is-text has-text-weight-semibold" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/courses/_course.html.erb
<div class="columns is-mobile is-vcentered">
  <div class="column is-narrow">
    <p class="is-size-5">
    <span class="icon is-large">
      <% if course.votes.pluck(:voter_id).include?(current_teacher.id) %>
        <%= link_to course_vote_path(course), method: :delete, class: 'has-text-primary' do %>
          <i class="fas fa-heart"></i>
        <% end %>
      <% else %>
        <%= link_to course_vote_path(course), method: :post, class: 'has-text-primary' do %>
          <i class="far fa-heart"></i>
        <% end %>
      <% end %>
    </span>
    </p>
  </div>

  <div class="column">
    <p class="heading">
      Title
    </p>

    <p class="title is-4">
      <%= link_to course.title, course_path(course), class: 'has-text-dark' %>
    <p>
  </div>

  <div class="column is-narrow">
    <div class="has-text-centered">
      <p class="heading">
        Votes
      </p>

      <p class="title">
        <%= course.votes_count %>
      <p>
    </div>
  </div>

  <div class="column is-narrow">
    <div class="has-text-centered">
      <p class="heading">
        Teachers
      </p>

      <p class="title">
        <%= course.proposals_count %>
      <p>
    </div>
  </div>
</div>

app/views/courses/_form.html.erb
<%= form_with model: course, local: true do |f| %>
  <%= f.bulma_text_field_with_label :title %>
  <%= f.bulma_submit "Submit" %>
<% end %>

app/views/courses/_proposal.html.erb
<div class="columns is-mobile is-vcentered">
  <div class="column is-narrow">
    <p class="is-size-5">
      <span class="icon is-large">
        <% if proposal.votes.pluck(:voter_id).include?(current_teacher.id) %>
          <%= link_to proposal_vote_path(proposal), method: :delete, class: 'has-text-primary' do %>
            <i class="fas fa-heart"></i>
          <% end %>
        <% else %>
          <%= link_to proposal_vote_path(proposal), method: :post, class: 'has-text-primary' do %>
            <i class="far fa-heart"></i>
          <% end %>
        <% end %>
      </span>
    </p>
  </div>

  <div class="column">
    <p class="heading">
      Teacher Name
    </p>

    <p class="title is-4">
      <%= proposal.teacher.name %>
    <p>
  </div>

  <div class="column is-narrow">
    <div class="has-text-centered">
      <p class="heading">
        Votes
      </p>

      <p class="title">
        <%= proposal.votes_count %>
      <p>
    </div>
  </div>
</div>

app/views/courses/index.html.erb
<section>
  <div class="container">
    <div class="columns is-vcentered">
      <div class="column">
        <h3 class="title is-6 is-uppercase">
          <%= "Courses (#{courses.size})" %>
        </h3>
      </div>

      <div class="column is-narrow">
        <%= link_to new_course_path, class: "button is-primary is-small is-uppercase" do %>
          <span class="icon">
            <i class="fas fa-plus"></i>
          </span>

          <span>Register a course</span>
        <% end %>
      </div>
    </div>

    <% if courses.blank? %>
      <div class="block has-text-centered mt-6">
        <p class="subtitle">
          There are none available courses.
        </p>
      <div>
    <% else %>
      <%= render partial: "course", collection: courses %>
    <% end %>
  </div>
</section>

app/views/courses/new.html.erb
<section>
  <div class="container">
    <h3 class="title">New Course.</h3>

    <div class="columns">
      <div class="column is-half">
        <%= render "form", course: @course %>
      </div>
    </div>
  </div>
</section>

app/views/courses/show.html.erb
<section>
  <div class="container">
    <h3 class="title is-6 is-uppercase">
      COURSE
    </h3>

    <%= render "course", course: @course %>

    <div class="columns is-vcentered">
      <div class="column">
        <h3 class="title is-6 is-uppercase">
          <%= "Registered Teachers (#{@proposals.size})" %>
        </h3>
      </div>

      <div class="column is-narrow">
        <% if @course.proposals.where(teacher: current_teacher).any? %>
          <%= link_to course_proposal_path(@course), method: :delete, class: "button is-primary is-small is-uppercase" do %>
            <span class="icon">
              <i class="fas fa-user-slash"></i>
            </span>

            <span>Unroll me</span>
          <% end %>
        <% else %>
          <%= link_to course_proposal_path(@course), method: :post, class: "button is-primary is-small is-uppercase" do %>
            <span class="icon">
              <i class="fas fa-user-plus"></i>
            </span>

            <span>Register me</span>
          <% end %>
        <% end %>
      </div>
    </div>

    <% if @proposals.empty? %>
      <div class="block has-text-centered mt-6">
        <p class="subtitle">
          There are none registered teachers.
        </p>
      <div>
    <% else %>
      <%= render partial: "proposal", collection: @proposals %>
    <% end %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="has-navbar-fixed-top">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Domestika</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "navbar" %>

    <section class="section">
      <%= yield %>
    </section>
  </body>
</html>

app/views/teachers/_form.html.erb
<%= form_with model: teacher, local: true do |f| %>
  <%= f.bulma_text_field_with_label :name %>
  <%= f.bulma_text_field_with_label :email %>
  <%= f.bulma_password_field_with_label :password %>
  <%= f.bulma_submit "Register" %>
<% end %>

app/views/teachers/new.html.erb
<section class="hero is-large">
  <div class="hero-body">
    <div class="container">
      <h3 class="title">Sign Up.</h3>

      <p class="subtitle">
        Already have an account? Log in <%= link_to "here", new_session_path, class: "has-text-primary is-underlined" %>.
      </p>

      <div class="columns">
        <div class="column is-half">
          <%= render "form", teacher: teacher %>
        </div>
      </div>
    </div>
  </div>
</section>